# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88e059e6df653661d1c7664e7a55b48002fa964c528672d2aefb24e9070d6bb22728860c6de8f4f6898e3858ff17de3af9a3b7d36a001afa39be4499d7b88623

test:
  secret_key_base: 4e0fd3b62f5a4a87cff44875ebfd8688f0fa410d123e5d655b00d6022d4ac2a9fd870af000b595defd25594ff1e6c5496dd78845d1d40b4b347c01cbcc207d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
